
name: Node.js CD

on:
  push:
    branches: [ main ] # Runs every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Move to home directory
            cd /home/ubuntu
            
            # 2. Clone if it doesn't exist, otherwise pull latest
            if [ ! -d "hello-app" ]; then
              git clone git@github.com:Husain-Vora/hello-app.git
            fi
            
            # 3. Enter the folder and update
            cd hello-app
            git pull origin main
            npm install
            
            # 4. Restart the app (pointing to the correct file location)
            pm2 delete hello-app || true
            pm2 start index.js --name "hello-app"
